import{describe,expect,it}from'vitest';
import{evaluateProductionReadiness,productionGates,type GateEvidence}from'./production-readiness.js';
const digest=`sha256:${'a'.repeat(64)}`;
const schema='b'.repeat(32);
const evidence:GateEvidence[]=productionGates.map(gate=>({gate,controlVersion:'mvp-production-gate-v1',result:'Passed',environmentId:'production-apne1',releaseArtifactDigest:digest,schemaFingerprint:schema,evidenceReferences:[`evidence://${gate}`],executedAt:new Date(0),expiresAt:new Date(2000),humanOwner:`owner-${gate}`,humanApprover:`approver-${gate}`}));
describe('Production readiness gate',()=>{
 it('approves only one complete unexpired evidence set for the exact artifact and schema',()=>{expect(evaluateProductionReadiness({environmentId:'production-apne1',releaseArtifactDigest:digest,schemaFingerprint:schema,now:new Date(1000),evidence,exceptions:[],criticalVulnerabilityCount:0})).toEqual({approved:true,blockers:[]});});
 it('blocks expired evidence, placeholder ownership, artifact mismatch, and critical vulnerabilities',()=>{const altered=evidence.map((item,index)=>index===0?{...item,humanOwner:'TBD',expiresAt:new Date(500)}:item);const result=evaluateProductionReadiness({environmentId:'production-apne1',releaseArtifactDigest:digest,schemaFingerprint:schema,now:new Date(1000),evidence:altered,exceptions:[],criticalVulnerabilityCount:1});expect(result.approved).toBe(false);expect(result.blockers).toEqual(expect.arrayContaining(['Unresolved critical vulnerabilities exist','DomainAuthority evidence is expired','DomainAuthority has no named Human owner']));});
 it('never permits an exception for a non-waivable invariant',()=>{const failed=evidence.map((item,index)=>index===0?{...item,result:'Failed' as const,exceptionReference:'exception-a'}:item);const result=evaluateProductionReadiness({environmentId:'production-apne1',releaseArtifactDigest:digest,schemaFingerprint:schema,now:new Date(1000),evidence:failed,exceptions:[{exceptionReference:'exception-a',gate:'DomainAuthority',expiresAt:new Date(2000),approvedByHuman:'security-owner',blastRadius:'production',compensatingControl:'none',remediation:'fix',nonWaivableInvariantAffected:true}],criticalVulnerabilityCount:0});expect(result.approved).toBe(false);});
});
