export type FailureCategory='TransientInfrastructure'|'TransientConcurrency'|'TransientExternalDependency'|'PermanentContract'|'PermanentSecurity'|'PermanentDomain'|'Configuration'|'Unknown';
export interface RetryProfile{readonly version:string;readonly maximumAttempts:number;readonly maximumElapsedMs:number;readonly baseDelayMs:number;readonly maximumDelayMs:number;readonly retryable:readonly FailureCategory[];readonly unknownAttempts:number;}
export const retryProfiles={
 'outbox-local-v1':{version:'outbox-local-v1',maximumAttempts:10,maximumElapsedMs:900000,baseDelayMs:500,maximumDelayMs:30000,retryable:['TransientInfrastructure','TransientConcurrency']as const,unknownAttempts:3},
 'postgres-local-v1':{version:'postgres-local-v1',maximumAttempts:8,maximumElapsedMs:900000,baseDelayMs:500,maximumDelayMs:30000,retryable:['TransientInfrastructure','TransientConcurrency']as const,unknownAttempts:3},
 'memory-generation-v1':{version:'memory-generation-v1',maximumAttempts:5,maximumElapsedMs:86400000,baseDelayMs:30000,maximumDelayMs:900000,retryable:['TransientInfrastructure','TransientExternalDependency']as const,unknownAttempts:0}
}as const satisfies Readonly<Record<string,RetryProfile>>;
function hash32(value:string):number{let hash=2166136261;for(let index=0;index<value.length;index+=1){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619);}return hash>>>0;}
export function retryDecision(input:{profile:RetryProfile;category:FailureCategory;operationIdentity:string;attemptCount:number;elapsedMs:number;databaseNow:Date}):{readonly retry:false}|{readonly retry:true;readonly delayMs:number;readonly nextAttemptAt:Date}{const{profile,category,attemptCount,elapsedMs}=input;const allowed=profile.retryable.includes(category)||category==='Unknown'&&attemptCount<=profile.unknownAttempts;if(!allowed||attemptCount>=profile.maximumAttempts||elapsedMs>=profile.maximumElapsedMs)return{retry:false};const exponent=Math.min(attemptCount-1,30);const cap=Math.min(profile.maximumDelayMs,profile.baseDelayMs*2**Math.max(0,exponent));const seed=hash32(`${input.operationIdentity}:${String(attemptCount)}:${profile.version}`);const delayMs=seed%(cap+1);if(elapsedMs+delayMs>profile.maximumElapsedMs)return{retry:false};return{retry:true,delayMs,nextAttemptAt:new Date(input.databaseNow.getTime()+delayMs)};}
