export type DecisionStatus='Draft'|'InReview'|'Approved'|'Rejected'|'Withdrawn';
export type DecisionOutcome='Approved'|'Rejected'|'Withdrawn';
export type HumanDecisionActor={readonly actorType:'HumanMember';readonly identityId:string;readonly membershipId:string};
export type DecisionContent={readonly title:string;readonly summary:string;readonly rationale:string;readonly proposal:string;readonly supportingReferences:readonly string[]};
export interface DecisionRevision{readonly revisionId:string;readonly revisionNumber:number;readonly status:'Draft'|'Submitted'|'Approved'|'Rejected'|'Withdrawn';readonly content:DecisionContent;readonly contentHash?:string|undefined;readonly submittedAt?:Date|undefined;readonly createdBy:HumanDecisionActor;}
export interface DecisionReview{readonly reviewId:string;readonly revisionId:string;readonly outcome:DecisionOutcome;readonly reviewer:HumanDecisionActor;readonly rationale?:string|undefined;readonly reviewedAt:Date;}
export interface DecisionState{readonly decisionId:string;readonly organizationId:string;readonly relatedWorkId:string;readonly isBlocking:boolean;readonly status:DecisionStatus;readonly revisions:readonly DecisionRevision[];readonly reviews:readonly DecisionReview[];readonly version:number;readonly createdBy:HumanDecisionActor;readonly createdAt:Date;readonly updatedAt:Date;}
export type DecisionEventType='DecisionCreated'|'DecisionDraftEdited'|'DecisionSubmitted'|'DecisionApproved'|'DecisionRejected'|'DecisionWithdrawn'|'DecisionRevisionStarted';
export interface DecisionEvent{readonly eventId:string;readonly eventType:DecisionEventType;readonly decisionId:string;readonly organizationId:string;readonly relatedWorkId:string;readonly aggregateVersion:number;readonly actor:HumanDecisionActor;readonly occurredAt:Date;readonly payload:Readonly<Record<string,unknown>>;}
export interface SubmittedDecisionReference{readonly decisionId:string;readonly revisionNumber:number;readonly submittedSnapshotId:string;}
export class DecisionInvariantViolation extends Error{}

const validContent=(content:DecisionContent):boolean=>content.title.trim().length>0&&content.title.length<=200&&content.summary.trim().length>0&&content.summary.length<=10000&&content.rationale.trim().length>0&&content.rationale.length<=10000&&content.proposal.trim().length>0&&content.proposal.length<=20000;

export class Decision{
  private events:DecisionEvent[]=[];
  private constructor(private current:DecisionState,private readonly ids:{eventId:()=>string;revisionId:()=>string;reviewId:()=>string;hash:(content:DecisionContent)=>string}){}
  static create(input:{decisionId:string;organizationId:string;relatedWorkId:string;isBlocking:boolean;content:DecisionContent;actor:HumanDecisionActor;now:Date;ids:{eventId:()=>string;revisionId:()=>string;reviewId:()=>string;hash:(content:DecisionContent)=>string}}):Decision{
    if(!validContent(input.content))throw new DecisionInvariantViolation('Decision content is invalid');
    const revision:DecisionRevision={revisionId:input.ids.revisionId(),revisionNumber:1,status:'Draft',content:input.content,createdBy:input.actor};
    const decision=new Decision({decisionId:input.decisionId,organizationId:input.organizationId,relatedWorkId:input.relatedWorkId,isBlocking:input.isBlocking,status:'Draft',revisions:[revision],reviews:[],version:1,createdBy:input.actor,createdAt:input.now,updatedAt:input.now},input.ids);
    decision.emit('DecisionCreated',input.actor,input.now,{revisionNumber:1});return decision;
  }
  static rehydrate(state:DecisionState,ids:{eventId:()=>string;revisionId:()=>string;reviewId:()=>string;hash:(content:DecisionContent)=>string}):Decision{return new Decision(state,ids);}
  get state():DecisionState{return this.current;}
  pullEvents():readonly DecisionEvent[]{const result=this.events;this.events=[];return result;}
  editDraft(actor:HumanDecisionActor,content:DecisionContent,now:Date):void{this.requireStatus('Draft');if(!validContent(content))throw new DecisionInvariantViolation('Decision content is invalid');const draft=this.activeRevision();this.replaceRevision({...draft,content});this.bump('DecisionDraftEdited',actor,now,{revisionNumber:draft.revisionNumber});}
  submit(actor:HumanDecisionActor,now:Date):SubmittedDecisionReference{this.requireStatus('Draft');const draft=this.activeRevision();if(!validContent(draft.content))throw new DecisionInvariantViolation('Decision content is incomplete');const submitted={...draft,status:'Submitted' as const,contentHash:this.ids.hash(draft.content),submittedAt:now};this.replaceRevision(submitted);this.current={...this.current,status:'InReview'};this.bump('DecisionSubmitted',actor,now,{revisionNumber:submitted.revisionNumber,submittedSnapshotId:submitted.revisionId});return{decisionId:this.current.decisionId,revisionNumber:submitted.revisionNumber,submittedSnapshotId:submitted.revisionId};}
  approve(actor:HumanDecisionActor,rationale:string|undefined,now:Date):void{this.resolve('Approved','DecisionApproved',actor,rationale,now);}
  reject(actor:HumanDecisionActor,rationale:string|undefined,now:Date):void{this.resolve('Rejected','DecisionRejected',actor,rationale,now);}
  withdraw(actor:HumanDecisionActor,rationale:string|undefined,now:Date):void{this.resolve('Withdrawn','DecisionWithdrawn',actor,rationale,now);}
  startRevision(actor:HumanDecisionActor,content:DecisionContent,now:Date):void{if(this.current.status!=='Rejected'&&this.current.status!=='Withdrawn')throw new DecisionInvariantViolation('A new revision requires a rejected or withdrawn Decision');if(!validContent(content))throw new DecisionInvariantViolation('Decision content is invalid');const previous=this.activeRevision();const revision:DecisionRevision={revisionId:this.ids.revisionId(),revisionNumber:previous.revisionNumber+1,status:'Draft',content,createdBy:actor};this.current={...this.current,status:'Draft',revisions:[...this.current.revisions,revision]};this.bump('DecisionRevisionStarted',actor,now,{revisionNumber:revision.revisionNumber,basedOnRevisionNumber:previous.revisionNumber});}
  submittedReference():SubmittedDecisionReference{const revision=this.activeRevision();if(this.current.status!=='InReview'||revision.status!=='Submitted')throw new DecisionInvariantViolation('Decision has no active submitted snapshot');return{decisionId:this.current.decisionId,revisionNumber:revision.revisionNumber,submittedSnapshotId:revision.revisionId};}
  private resolve(outcome:DecisionOutcome,eventType:Extract<DecisionEventType,'DecisionApproved'|'DecisionRejected'|'DecisionWithdrawn'>,actor:HumanDecisionActor,rationale:string|undefined,now:Date):void{this.requireStatus('InReview');const revision=this.activeRevision();if(revision.status!=='Submitted')throw new DecisionInvariantViolation('Review must bind the submitted snapshot');const review:DecisionReview={reviewId:this.ids.reviewId(),revisionId:revision.revisionId,outcome,reviewer:actor,rationale,reviewedAt:now};this.replaceRevision({...revision,status:outcome});this.current={...this.current,status:outcome,reviews:[...this.current.reviews,review]};this.bump(eventType,actor,now,{revisionNumber:revision.revisionNumber,submittedSnapshotId:revision.revisionId,reviewRecordId:review.reviewId,outcome,rationale:rationale??null});}
  private activeRevision():DecisionRevision{const revision=this.current.revisions[this.current.revisions.length-1];if(!revision)throw new DecisionInvariantViolation('Decision must have a revision');return revision;}
  private replaceRevision(revision:DecisionRevision):void{this.current={...this.current,revisions:this.current.revisions.map(item=>item.revisionId===revision.revisionId?revision:item)};}
  private requireStatus(status:DecisionStatus):void{if(this.current.status!==status)throw new DecisionInvariantViolation(`Expected ${String(status)} Decision`);}
  private bump(eventType:DecisionEventType,actor:HumanDecisionActor,occurredAt:Date,payload:Readonly<Record<string,unknown>>):void{this.current={...this.current,version:this.current.version+1,updatedAt:occurredAt};this.emit(eventType,actor,occurredAt,payload);}
  private emit(eventType:DecisionEventType,actor:HumanDecisionActor,occurredAt:Date,payload:Readonly<Record<string,unknown>>):void{this.events.push({eventId:this.ids.eventId(),eventType,decisionId:this.current.decisionId,organizationId:this.current.organizationId,relatedWorkId:this.current.relatedWorkId,aggregateVersion:this.current.version,actor,occurredAt,payload});}
}
