-- 0001_baseline.sql
--
-- The schema as it stood when ADR-0020 adopted migrations: the output of
-- `scripts/extract_schema.py`, frozen.
--
-- This is not a claim about history. Every database that existed at the time was
-- built by applying exactly this, so the baseline is the state every environment
-- was already in — which is what lets an existing database adopt the ledger
-- without being rebuilt.
--
-- Do not edit this file. `scripts/migrate.py` records a checksum and refuses to
-- run when an applied migration has changed underneath it. A correction to the
-- schema is a new migration and a matching edit to
-- `docs/architecture/persistence-and-data-model.md`, which
-- `scripts/check_migrations.py` proves stay equal.

CREATE TABLE human_identities (
    identity_id                 uuid PRIMARY KEY,
    status                      text NOT NULL,
    display_name                text NOT NULL,
    primary_email               text NULL,
    primary_email_normalized    text NULL,
    locale                      text NULL,

    version                     bigint NOT NULL,
    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,
    disabled_at                 timestamptz NULL,


    CONSTRAINT ck_human_identities_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_human_identities_disabled_at
        CHECK (
            (status = 'Disabled') = (disabled_at IS NOT NULL)
        )
);

CREATE TABLE organizations (
    organization_id             uuid PRIMARY KEY,
    name                        text NOT NULL,
    status                      text NOT NULL,
    created_by_identity_id      uuid NOT NULL,

    version                     bigint NOT NULL,
    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,

    suspended_at                timestamptz NULL,
    suspension_reason           text NULL,
    archived_at                 timestamptz NULL,
    archive_reason              text NULL,

    CONSTRAINT fk_organizations_created_by_identity
        FOREIGN KEY (
            created_by_identity_id
        )
        REFERENCES human_identities (
            identity_id
        ),


    CONSTRAINT ck_organizations_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_organizations_suspended_at
        CHECK (
            (status = 'Suspended') = (suspended_at IS NOT NULL)
        ),

    CONSTRAINT ck_organizations_archived_at
        CHECK (
            (status = 'Archived') = (archived_at IS NOT NULL)
        )
);

CREATE TABLE authentication_subjects (
    authentication_subject_id   uuid PRIMARY KEY,
    identity_id                 uuid NOT NULL,
    provider                    text NOT NULL,
    issuer                      text NOT NULL,
    subject                     text NOT NULL,

    linked_at                   timestamptz NOT NULL,
    unlinked_at                 timestamptz NULL,
    created_at                  timestamptz NOT NULL,

    CONSTRAINT fk_authentication_subjects_identity
        FOREIGN KEY (
            identity_id
        )
        REFERENCES human_identities (
            identity_id
        )
);

CREATE TABLE memberships (
    membership_id                   uuid PRIMARY KEY,
    organization_id                 uuid NOT NULL,
    identity_id                     uuid NULL,

    pending_invitee_email           text NULL,
    pending_invitee_email_normalized text NULL,

    status                          text NOT NULL,

    invited_by_identity_id          uuid NULL,
    invited_by_membership_id        uuid NULL,
    invited_at                      timestamptz NULL,
    activated_at                    timestamptz NULL,

    suspended_by_identity_id        uuid NULL,
    suspended_at                    timestamptz NULL,
    suspension_reason               text NULL,

    revoked_by_identity_id          uuid NULL,
    revoked_at                      timestamptz NULL,
    revocation_reason               text NULL,

    version                         bigint NOT NULL,
    created_at                      timestamptz NOT NULL,
    updated_at                      timestamptz NOT NULL,

    CONSTRAINT uq_memberships_organization_membership
        UNIQUE (
            organization_id,
            membership_id
        ),

    CONSTRAINT fk_memberships_organization
        FOREIGN KEY (
            organization_id
        )
        REFERENCES organizations (
            organization_id
        ),

    CONSTRAINT fk_memberships_identity
        FOREIGN KEY (
            identity_id
        )
        REFERENCES human_identities (
            identity_id
        ),


    CONSTRAINT ck_memberships_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_memberships_revoked_at
        CHECK (
            (status = 'Revoked') = (revoked_at IS NOT NULL)
        )
);

CREATE TABLE membership_role_assignments (
    role_assignment_id          uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    membership_id               uuid NOT NULL,
    role                        text NOT NULL,

    assigned_by_identity_id     uuid NOT NULL,
    assigned_by_membership_id   uuid NOT NULL,
    assigned_at                 timestamptz NOT NULL,

    revoked_by_identity_id      uuid NULL,
    revoked_by_membership_id    uuid NULL,
    revoked_at                  timestamptz NULL,
    revocation_reason           text NULL,

    CONSTRAINT fk_membership_role_assignments_membership
        FOREIGN KEY (
            organization_id,
            membership_id
        )
        REFERENCES memberships (
            organization_id,
            membership_id
        ),


    CONSTRAINT ck_membership_role_assignments_revocation
        CHECK (
            (revoked_at IS NULL) = (revoked_by_identity_id IS NULL)
        )
);

CREATE TABLE organization_invitations (
    invitation_id               uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    membership_id               uuid NOT NULL,
    invitation_version          integer NOT NULL,

    token_hash                  text NOT NULL,
    status                      text NOT NULL,

    expires_at                  timestamptz NOT NULL,
    consumed_at                 timestamptz NULL,
    revoked_at                  timestamptz NULL,
    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,

    CONSTRAINT fk_organization_invitations_membership
        FOREIGN KEY (
            organization_id,
            membership_id
        )
        REFERENCES memberships (
            organization_id,
            membership_id
        ),


    CONSTRAINT ck_organization_invitations_version
        CHECK (
            invitation_version > 0
        ),

    CONSTRAINT ck_organization_invitations_consumed_at
        CHECK (
            (status = 'Consumed') = (consumed_at IS NOT NULL)
        ),

    CONSTRAINT ck_organization_invitations_revoked_at
        CHECK (
            (status = 'Revoked') = (revoked_at IS NOT NULL)
        )
);

CREATE TABLE work_items (
    work_id                     uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    title                        text NOT NULL,
    description                  text NULL,
    status                       text NOT NULL,
    completion_gate_type         text NOT NULL,
    completion_gate_decision_id  uuid NULL,
    completion_gate_revision_number integer NULL,
    completion_gate_submitted_snapshot_id uuid NULL,
    blocking_decision_id         uuid NULL,
    blocking_decision_revision_number integer NULL,
    blocking_decision_submitted_snapshot_id uuid NULL,
    decision_outcome             text NULL,

    created_by_identity_id       uuid NOT NULL,
    created_by_membership_id     uuid NOT NULL,

    started_by_identity_id       uuid NULL,
    started_at                   timestamptz NULL,

    completed_by_identity_id     uuid NULL,
    completed_by_membership_id   uuid NULL,
    completion_summary           text NULL,
    completed_at                 timestamptz NULL,

    cancelled_by_identity_id     uuid NULL,
    cancelled_by_membership_id   uuid NULL,
    cancellation_reason          text NULL,
    cancelled_at                 timestamptz NULL,

    version                      bigint NOT NULL,
    created_at                   timestamptz NOT NULL,
    updated_at                   timestamptz NOT NULL,

    CONSTRAINT uq_work_items_organization_work
        UNIQUE (
            organization_id,
            work_id
        ),

    CONSTRAINT fk_work_items_organization
        FOREIGN KEY (
            organization_id
        )
        REFERENCES organizations (
            organization_id
        ),

    CONSTRAINT ck_work_items_version
        CHECK (
            version > 0
        )
);

CREATE TABLE work_participants (
    work_participant_id     uuid PRIMARY KEY,
    organization_id         uuid NOT NULL,
    work_id                 uuid NOT NULL,
    membership_id           uuid NOT NULL,
    relationship_type       text NOT NULL,

    added_by_identity_id    uuid NOT NULL,
    added_by_membership_id  uuid NOT NULL,
    added_at                timestamptz NOT NULL,

    removed_by_identity_id  uuid NULL,
    removed_by_membership_id uuid NULL,
    removed_at              timestamptz NULL,

    CONSTRAINT ck_work_participants_relationship_type CHECK (
        relationship_type IN ('Assignee', 'Participant', 'Observer')
    ),

    CONSTRAINT ck_work_participants_removal CHECK (
        (removed_at IS NULL
            AND removed_by_identity_id IS NULL
            AND removed_by_membership_id IS NULL)
        OR (removed_at IS NOT NULL
            AND removed_by_identity_id IS NOT NULL
            AND removed_by_membership_id IS NOT NULL)
    ),

    CONSTRAINT ck_work_participants_removed_after_added CHECK (
        removed_at IS NULL OR removed_at >= added_at
    ),

    FOREIGN KEY (organization_id, work_id)
        REFERENCES work_items (organization_id, work_id),

    FOREIGN KEY (organization_id, membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE work_progress_records (
    work_progress_record_id uuid PRIMARY KEY,
    organization_id         uuid NOT NULL,
    work_id                 uuid NOT NULL,

    content                 text NOT NULL,

    recorded_by_identity_id   uuid NOT NULL,
    recorded_by_membership_id uuid NOT NULL,
    recorded_at             timestamptz NOT NULL,

    CONSTRAINT ck_work_progress_records_content CHECK (
        length(btrim(content)) > 0
    ),

    FOREIGN KEY (organization_id, work_id)
        REFERENCES work_items (organization_id, work_id),

    FOREIGN KEY (organization_id, recorded_by_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE decisions (
    decision_id                  uuid PRIMARY KEY,
    organization_id              uuid NOT NULL,
    related_work_id              uuid NOT NULL,
    is_blocking                  boolean NOT NULL,
    status                        text NOT NULL,

    current_revision_id           uuid NULL,
    current_revision_number       integer NOT NULL,

    created_by_identity_id        uuid NOT NULL,
    created_by_membership_id      uuid NOT NULL,

    submitted_revision_id         uuid NULL,
    submitted_by_identity_id      uuid NULL,
    submitted_by_membership_id    uuid NULL,
    submitted_at                  timestamptz NULL,

    decided_revision_id           uuid NULL,
    outcome                       text NULL,
    decided_by_identity_id        uuid NULL,
    decided_by_membership_id      uuid NULL,
    review_rationale              text NULL,
    decided_at                    timestamptz NULL,

    version                       bigint NOT NULL,
    created_at                    timestamptz NOT NULL,
    updated_at                    timestamptz NOT NULL,

    CONSTRAINT uq_decisions_organization_decision
        UNIQUE (
            organization_id,
            decision_id
        ),

    CONSTRAINT ck_decisions_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_decisions_revision_number
        CHECK (
            current_revision_number > 0
        )
);

CREATE TABLE decision_revisions (
    decision_revision_id        uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    decision_id                 uuid NOT NULL,
    revision_number             integer NOT NULL,
    revision_status             text NOT NULL,

    title                       text NOT NULL,
    question                    text NOT NULL,
    context                     text NULL,
    options                     jsonb NOT NULL DEFAULT '[]'::jsonb,
    rationale                   text NULL,

    created_by_identity_id      uuid NOT NULL,
    created_by_membership_id    uuid NOT NULL,

    reviewed_by_identity_id     uuid NULL,
    reviewed_by_membership_id   uuid NULL,
    reviewed_at                 timestamptz NULL,
    review_rationale            text NULL,
    selected_option_id          text NULL,

    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,

    CONSTRAINT uq_decision_revisions_organization_revision
        UNIQUE (
            organization_id,
            decision_revision_id
        ),

    CONSTRAINT fk_decision_revisions_decision
        FOREIGN KEY (
            organization_id,
            decision_id
        )
        REFERENCES decisions (
            organization_id,
            decision_id
        ),

    CONSTRAINT ck_decision_revisions_selected_option
        CHECK (
            selected_option_id IS NULL
            OR revision_status = 'Approved'
        )
);

CREATE TABLE decision_secretary_contributions (
    contribution_id            uuid PRIMARY KEY,
    organization_id            uuid NOT NULL,
    decision_id                uuid NOT NULL,
    decision_revision_id       uuid NOT NULL,

    secretary_principal_id     text NOT NULL,
    requested_by_identity_id   uuid NOT NULL,
    requested_by_membership_id uuid NOT NULL,

    contribution_type          text NOT NULL,
    content                    text NOT NULL,
    generation_id              uuid NOT NULL,

    created_at                 timestamptz NOT NULL,
    adopted_at                 timestamptz NULL,
    adopted_by_identity_id     uuid NULL,

    CONSTRAINT ck_decision_contributions_content CHECK (
        length(btrim(content)) > 0
    ),

    CONSTRAINT ck_decision_contributions_adoption CHECK (
        (adopted_at IS NULL) = (adopted_by_identity_id IS NULL)
    ),

    FOREIGN KEY (organization_id, decision_id)
        REFERENCES decisions (organization_id, decision_id),

    FOREIGN KEY (organization_id, requested_by_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE secretary_assistance_grants (
    grant_id                 uuid PRIMARY KEY,
    organization_id          uuid NOT NULL,
    secretary_principal_id   text NOT NULL,
    context_key              text NOT NULL,
    assistance_operation     text NOT NULL,
    port_contract_version    integer NOT NULL,

    granted_at               timestamptz NOT NULL,
    granted_by_membership_id uuid NOT NULL,
    revoked_at               timestamptz NULL,
    revoked_by_membership_id uuid NULL,
    reason                   text NOT NULL,

    CONSTRAINT ck_secretary_grants_revocation CHECK (
        (revoked_at IS NULL) = (revoked_by_membership_id IS NULL)
    ),

    FOREIGN KEY (organization_id, granted_by_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE memories (
    memory_id                         uuid PRIMARY KEY,
    organization_id                   uuid NOT NULL,
    source_work_id                    uuid NOT NULL,
    source_snapshot_id                uuid NOT NULL,
    source_snapshot_hash              text NOT NULL,
    status                            text NOT NULL,
    is_active                         boolean NOT NULL,

    current_revision_id               uuid NOT NULL,
    current_revision_number           integer NOT NULL,

    generation_policy_version         integer NOT NULL,
    generated_by_system_principal_id  text NOT NULL,
    generated_at                      timestamptz NOT NULL,

    submitted_revision_id             uuid NULL,
    submitted_by_identity_id          uuid NULL,
    submitted_by_membership_id        uuid NULL,
    submitted_at                      timestamptz NULL,

    reviewed_revision_id              uuid NULL,
    reviewed_by_identity_id           uuid NULL,
    reviewed_by_membership_id         uuid NULL,
    review_note                       text NULL,
    reviewed_at                       timestamptz NULL,

    version                           bigint NOT NULL,
    created_at                        timestamptz NOT NULL,
    updated_at                        timestamptz NOT NULL,

    CONSTRAINT uq_memories_organization_memory
        UNIQUE (
            organization_id,
            memory_id
        ),

    CONSTRAINT ck_memories_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_memories_revision_number
        CHECK (
            current_revision_number > 0
        ),

    CONSTRAINT ck_memories_generation_policy
        CHECK (
            generation_policy_version > 0
        )
);

CREATE TABLE memory_revisions (
    memory_revision_id          uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    memory_id                   uuid NOT NULL,
    revision_number             integer NOT NULL,
    revision_status             text NOT NULL,

    title                       text NOT NULL,
    summary                     text NOT NULL,
    content                     text NOT NULL,
    source_references           jsonb NOT NULL DEFAULT '[]'::jsonb,

    created_by_actor_type       text NOT NULL,
    created_by_actor_id         uuid NOT NULL,
    created_by_membership_id    uuid NULL,

    content_hash                text NOT NULL,
    source_revision_id          uuid NULL,

    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,
    locked_at                   timestamptz NULL,

    CONSTRAINT uq_memory_revisions_organization_revision
        UNIQUE (
            organization_id,
            memory_revision_id
        ),

    CONSTRAINT fk_memory_revisions_memory
        FOREIGN KEY (
            organization_id,
            memory_id
        )
        REFERENCES memories (
            organization_id,
            memory_id
        ),

    CONSTRAINT ck_memory_revisions_actor_type
        CHECK (
            created_by_actor_type IN (
                'HumanMember',
                'AI',
                'System'
            )
        ),

    CONSTRAINT ck_memory_revisions_membership
        CHECK (
            created_by_actor_type <> 'HumanMember'
            OR created_by_membership_id IS NOT NULL
        )
);

CREATE TABLE memory_generation_operations (
    generation_operation_id     uuid PRIMARY KEY,
    organization_id             uuid NOT NULL,
    work_id                     uuid NOT NULL,

    source_event_id             uuid NOT NULL,
    source_snapshot_id          uuid NOT NULL,
    source_snapshot_hash        text NOT NULL,
    provider_input_hash         text NOT NULL,
    generation_policy_version    integer NOT NULL,

    status                      text NOT NULL,
    attempt_count               integer NOT NULL,
    next_attempt_at             timestamptz NULL,

    locked_by                   text NULL,
    locked_until                timestamptz NULL,
    claim_version               integer NOT NULL,

    first_started_at            timestamptz NULL,
    last_attempt_at             timestamptz NULL,
    completed_at                timestamptz NULL,

    model_reference             text NULL,
    prompt_template_version     integer NOT NULL,
    output_schema_version       integer NOT NULL,

    last_error_code             text NULL,
    error_reference             text NULL,

    memory_id                   uuid NULL,

    version                     bigint NOT NULL,
    created_at                  timestamptz NOT NULL,
    updated_at                  timestamptz NOT NULL,

    CONSTRAINT fk_memory_generation_operations_work
        FOREIGN KEY (
            organization_id,
            work_id
        )
        REFERENCES work_items (
            organization_id,
            work_id
        ),

    CONSTRAINT fk_memory_generation_operations_memory
        FOREIGN KEY (
            organization_id,
            memory_id
        )
        REFERENCES memories (
            organization_id,
            memory_id
        ),

    CONSTRAINT ck_memory_generation_operations_version
        CHECK (
            version > 0
        ),

    CONSTRAINT ck_memory_generation_operations_attempts
        CHECK (
            attempt_count >= 0
            AND claim_version >= 0
        ),

    CONSTRAINT ck_memory_generation_operations_completed
        CHECK (
            (status = 'Generated') = (completed_at IS NOT NULL)
        ),

    CONSTRAINT ck_memory_generation_operations_memory_link
        CHECK (
            (status = 'Generated') = (memory_id IS NOT NULL)
        )
);

CREATE TABLE notifications (
    notification_id         uuid PRIMARY KEY,
    organization_id         uuid NOT NULL,
    recipient_membership_id uuid NOT NULL,

    notification_type       text NOT NULL,
    subject_type            text NOT NULL,
    subject_id              uuid NOT NULL,
    title                   text NOT NULL,

    source_event_id         uuid NOT NULL,
    occurred_at             timestamptz NOT NULL,

    acknowledged_at         timestamptz NULL,

    created_at              timestamptz NOT NULL,

    CONSTRAINT ck_notifications_title CHECK (length(btrim(title)) > 0),

    CONSTRAINT uq_notifications_recipient_event
        UNIQUE (recipient_membership_id, source_event_id),

    FOREIGN KEY (organization_id, recipient_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE authorization_audit_records (
    authorization_audit_id uuid PRIMARY KEY,
    request_id             uuid NOT NULL,
    command_id             uuid NULL,
    correlation_id         uuid NOT NULL,

    principal_id           text NOT NULL,
    principal_type         text NOT NULL,
    identity_id            uuid NULL,
    membership_id          uuid NULL,
    organization_id        uuid NULL,

    command_type           text NOT NULL,
    permission             text NULL,
    resource_type          text NULL,
    resource_id            text NULL,

    policy_id              text NOT NULL,
    policy_version         integer NOT NULL,

    outcome                text NOT NULL,
    reason_code            text NULL,

    previous_state         text NULL,
    next_state             text NULL,

    evaluated_at           timestamptz NOT NULL,
    resulting_event_id     uuid NULL,
    created_at             timestamptz NOT NULL,

    CONSTRAINT ck_authorization_audit_denial CHECK (
        outcome = 'Allow' OR reason_code IS NOT NULL
    ),

    CONSTRAINT ck_authorization_audit_allow_state CHECK (
        outcome = 'Allow' OR (previous_state IS NULL AND next_state IS NULL)
    )
);

CREATE TABLE outbox_messages (
    outbox_id              uuid PRIMARY KEY,
    event_id               uuid NOT NULL,
    event_type             text NOT NULL,
    event_category         text NOT NULL,
    schema_version         integer NOT NULL,
    aggregate_type         text NOT NULL,
    aggregate_id           text NOT NULL,
    aggregate_version      bigint NOT NULL,
    event_sequence         integer NOT NULL,
    organization_id        uuid NULL,
    payload                jsonb NOT NULL,
    headers                jsonb NOT NULL DEFAULT '{}'::jsonb,
    destination            text NOT NULL,
    consumer_set_version   text NULL,
    target_count           integer NULL,
    occurred_at            timestamptz NOT NULL,
    recorded_at            timestamptz NOT NULL,
    correlation_id         uuid NOT NULL,
    causation_id           uuid NULL,
    actor_reference        jsonb NULL,
    status                 text NOT NULL,
    attempt_count          integer NOT NULL DEFAULT 0,
    next_attempt_at        timestamptz NOT NULL,
    first_attempt_at       timestamptz NULL,
    last_attempt_at        timestamptz NULL,
    published_at           timestamptz NULL,
    locked_by              text NULL,
    locked_until           timestamptz NULL,
    last_error_code        text NULL,
    last_error_message     text NULL
);

CREATE TABLE processed_events (
    consumer_name          text NOT NULL,
    event_id               uuid NOT NULL,
    event_type             text NOT NULL,
    schema_version         integer NOT NULL,
    organization_id        uuid NULL,
    aggregate_type         text NOT NULL,
    aggregate_id           text NOT NULL,
    aggregate_version      bigint NOT NULL,
    correlation_id         uuid NOT NULL,
    status                 text NOT NULL,
    attempt_count          integer NOT NULL DEFAULT 0,
    first_received_at      timestamptz NOT NULL,
    processing_started_at  timestamptz NULL,
    last_attempt_at        timestamptz NULL,
    next_attempt_at        timestamptz NULL,
    processed_at           timestamptz NULL,
    failed_at              timestamptz NULL,
    skipped_at             timestamptz NULL,
    handler_version        integer NULL,
    result_reference       jsonb NULL,
    last_error_code        text NULL,
    last_error_message     text NULL,
    locked_by              text NULL,
    locked_until           timestamptz NULL,
    claim_version          bigint NOT NULL DEFAULT 0,
    ordering_key_type      text NULL,
    ordering_key           text NULL,
    source_sequence        bigint NULL,
    blocked_by_event_id    uuid NULL,

    PRIMARY KEY (consumer_name, event_id),
    CHECK (attempt_count >= 0),
    CHECK (claim_version >= 0)
);

CREATE TABLE consumer_ordering_state (
    consumer_ordering_state_id uuid PRIMARY KEY,
    consumer_name           text NOT NULL,
    organization_id         uuid NULL,
    ordering_key_type       text NOT NULL,
    ordering_key            text NOT NULL,

    last_terminal_sequence  bigint NULL,
    blocked_event_id        uuid NULL,
    blocked_sequence        bigint NULL,
    blocked_at              timestamptz NULL,
    block_reason_code       text NULL,

    status                  text NOT NULL,
    version                 bigint NOT NULL DEFAULT 1,
    updated_at              timestamptz NOT NULL,

    CONSTRAINT ck_consumer_ordering_state_status CHECK (
        status IN ('Active', 'Blocked', 'Recovering')
    ),

    CONSTRAINT ck_consumer_ordering_state_blocked CHECK (
        (status = 'Blocked') =
        (blocked_event_id IS NOT NULL
            AND blocked_at IS NOT NULL
            AND block_reason_code IS NOT NULL)
    )
);

CREATE TABLE dead_letter_events (
    dead_letter_id          uuid PRIMARY KEY,
    organization_id         uuid NOT NULL,
    consumer_name           text NOT NULL,
    event_id                uuid NOT NULL,

    ordering_key_type       text NULL,
    ordering_key            text NULL,
    source_sequence         bigint NULL,

    failure_category        text NOT NULL,
    error_code              text NOT NULL,
    error_reference         text NULL,

    status                  text NOT NULL,
    assigned_to_identity_id uuid NULL,

    first_failed_at         timestamptz NOT NULL,
    last_failed_at          timestamptz NOT NULL,

    resolution_type         text NULL,
    resolution_reference    text NULL,
    resolution_reason_code  text NULL,
    resolved_by_identity_id   uuid NULL,
    resolved_by_membership_id uuid NULL,
    resolved_at             timestamptz NULL,
    replay_id               uuid NULL,

    version                 bigint NOT NULL DEFAULT 1,
    created_at              timestamptz NOT NULL,
    updated_at              timestamptz NOT NULL,

    CONSTRAINT uq_dead_letter_consumer_event UNIQUE (consumer_name, event_id),

    CONSTRAINT ck_dead_letter_status CHECK (
        status IN ('Open', 'Investigating', 'ReadyForReplay', 'Resolved', 'Skipped')
    ),

    CONSTRAINT ck_dead_letter_resolution CHECK (
        (status IN ('Resolved', 'Skipped')) =
        (resolved_at IS NOT NULL
            AND resolved_by_identity_id IS NOT NULL
            AND resolved_by_membership_id IS NOT NULL
            AND resolution_reason_code IS NOT NULL)
    ),

    FOREIGN KEY (organization_id, resolved_by_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE TABLE event_replays (
    replay_id               uuid PRIMARY KEY,
    organization_id         uuid NOT NULL,
    original_event_id       uuid NOT NULL,
    consumer_name           text NOT NULL,
    replay_mode             text NOT NULL,

    requested_by_identity_id   uuid NOT NULL,
    requested_by_membership_id uuid NOT NULL,
    reason_code             text NOT NULL,
    reason                  text NOT NULL,

    status                  text NOT NULL,

    authorization_policy_id      text NOT NULL,
    authorization_policy_version integer NOT NULL,
    authorized_at           timestamptz NOT NULL,

    source_processed_event_status  text NOT NULL,
    expected_dead_letter_version   bigint NULL,
    expected_ordering_state_version bigint NULL,

    attempt_count           integer NOT NULL DEFAULT 0,
    next_attempt_at         timestamptz NULL,
    locked_by               text NULL,
    locked_until            timestamptz NULL,
    claim_version           bigint NOT NULL DEFAULT 0,

    started_at              timestamptz NULL,
    completed_at            timestamptz NULL,
    result_code             text NULL,
    result_reference        text NULL,
    last_error_code         text NULL,
    error_reference         text NULL,

    version                 bigint NOT NULL DEFAULT 1,
    created_at              timestamptz NOT NULL,
    updated_at              timestamptz NOT NULL,

    CONSTRAINT ck_event_replays_mode CHECK (
        replay_mode IN (
            'RetryOriginal',
            'ReprocessWithCurrentHandler',
            'RebuildProjection',
            'ValidateOnly'
        )
    ),

    CONSTRAINT ck_event_replays_status CHECK (
        status IN (
            'Requested', 'Validating', 'Running',
            'Completed', 'Failed', 'Denied', 'Cancelled'
        )
    ),

    CONSTRAINT ck_event_replays_terminal CHECK (
        (status IN ('Completed', 'Failed', 'Denied', 'Cancelled'))
        = (completed_at IS NOT NULL)
    ),

    FOREIGN KEY (organization_id, requested_by_membership_id)
        REFERENCES memberships (organization_id, membership_id)
);

CREATE UNIQUE INDEX uq_memories_active_source_work
ON memories (
    organization_id,
    source_work_id
)
WHERE is_active = true;

ALTER TABLE work_items
ADD CONSTRAINT ck_work_items_status
CHECK (
    status IN (
        'Draft',
        'InProgress',
        'WaitingForDecision',
        'Completed',
        'Cancelled'
    )
);

ALTER TABLE work_items
ADD CONSTRAINT ck_work_items_completion_gate
CHECK (
    (
        completion_gate_type = 'NotRequired'
        AND completion_gate_decision_id IS NULL
        AND completion_gate_revision_number IS NULL
        AND completion_gate_submitted_snapshot_id IS NULL
        AND blocking_decision_id IS NULL
        AND blocking_decision_revision_number IS NULL
        AND blocking_decision_submitted_snapshot_id IS NULL
        AND decision_outcome IS NULL
    )
    OR
    (
        completion_gate_type = 'Pending'
        AND completion_gate_decision_id IS NOT NULL
        AND completion_gate_revision_number IS NOT NULL
        AND completion_gate_submitted_snapshot_id IS NOT NULL
        AND (
            (
                status = 'WaitingForDecision'
                AND blocking_decision_id = completion_gate_decision_id
                AND blocking_decision_revision_number = completion_gate_revision_number
                AND blocking_decision_submitted_snapshot_id = completion_gate_submitted_snapshot_id
            )
            OR
            (
                status = 'Cancelled'
                AND blocking_decision_id IS NULL
                AND blocking_decision_revision_number IS NULL
                AND blocking_decision_submitted_snapshot_id IS NULL
            )
        )
        AND decision_outcome IS NULL
    )
    OR
    (
        completion_gate_type = 'Satisfied'
        AND completion_gate_decision_id IS NOT NULL
        AND completion_gate_revision_number IS NOT NULL
        AND completion_gate_submitted_snapshot_id IS NOT NULL
        AND blocking_decision_id IS NULL
        AND blocking_decision_revision_number IS NULL
        AND blocking_decision_submitted_snapshot_id IS NULL
        AND decision_outcome = 'Approved'
    )
    OR
    (
        completion_gate_type = 'Unsatisfied'
        AND completion_gate_decision_id IS NOT NULL
        AND completion_gate_revision_number IS NOT NULL
        AND completion_gate_submitted_snapshot_id IS NOT NULL
        AND blocking_decision_id IS NULL
        AND blocking_decision_revision_number IS NULL
        AND blocking_decision_submitted_snapshot_id IS NULL
        AND decision_outcome IN (
            'Rejected',
            'Withdrawn'
        )
    )
);

ALTER TABLE work_items
ADD CONSTRAINT ck_work_items_completed_fields
CHECK (
    (
        status = 'Completed'
        AND completed_by_identity_id IS NOT NULL
        AND completed_by_membership_id IS NOT NULL
        AND completed_at IS NOT NULL
    )
    OR
    (
        status <> 'Completed'
        AND completed_at IS NULL
    )
);

ALTER TABLE work_items
ADD CONSTRAINT ck_work_items_cancelled_fields
CHECK (
    (
        status = 'Cancelled'
        AND cancelled_by_identity_id IS NOT NULL
        AND cancelled_by_membership_id IS NOT NULL
        AND cancelled_at IS NOT NULL
        AND cancellation_reason IS NOT NULL
    )
    OR
    (
        status <> 'Cancelled'
        AND cancelled_at IS NULL
    )
);

CREATE UNIQUE INDEX uq_work_participants_active_relationship
ON work_participants (
    work_id,
    membership_id,
    relationship_type
)
WHERE removed_at IS NULL;

CREATE INDEX ix_work_progress_records_work
ON work_progress_records (
    organization_id,
    work_id,
    recorded_at DESC
);

CREATE INDEX ix_work_items_organization_status
ON work_items (
    organization_id,
    status
);

CREATE INDEX ix_work_items_blocking_decision
ON work_items (
    organization_id,
    blocking_decision_id
)
WHERE blocking_decision_id IS NOT NULL;

CREATE INDEX ix_work_items_completed_at
ON work_items (
    organization_id,
    completed_at
)
WHERE status = 'Completed';

CREATE INDEX ix_work_participants_membership
ON work_participants (
    organization_id,
    membership_id
)
WHERE removed_at IS NULL;

ALTER TABLE decisions
ADD CONSTRAINT ck_decisions_status
CHECK (
    status IN (
        'Draft',
        'InReview',
        'Approved',
        'Rejected',
        'Withdrawn'
    )
);

ALTER TABLE decisions
ADD CONSTRAINT ck_decisions_outcome_state
CHECK (
    (
        status IN (
            'Draft',
            'InReview'
        )
        AND outcome IS NULL
    )
    OR
    (
        status = 'Approved'
        AND outcome = 'Approved'
    )
    OR
    (
        status = 'Rejected'
        AND outcome = 'Rejected'
    )
    OR
    (
        status = 'Withdrawn'
        AND outcome = 'Withdrawn'
    )
);

ALTER TABLE decisions
ADD CONSTRAINT ck_decisions_decided_fields
CHECK (
    (
        status IN (
            'Approved',
            'Rejected',
            'Withdrawn'
        )
        AND decided_revision_id IS NOT NULL
        AND decided_by_identity_id IS NOT NULL
        AND decided_by_membership_id IS NOT NULL
        AND decided_at IS NOT NULL
    )
    OR
    (
        status IN (
            'Draft',
            'InReview'
        )
        AND decided_at IS NULL
    )
);

ALTER TABLE decision_revisions
ADD CONSTRAINT ck_decision_revisions_number
CHECK (
    revision_number > 0
);

ALTER TABLE decision_revisions
ADD CONSTRAINT uq_decision_revisions_number
UNIQUE (
    decision_id,
    revision_number
);

CREATE UNIQUE INDEX uq_decision_revisions_one_draft
ON decision_revisions (
    decision_id
)
WHERE revision_status = 'Draft';

CREATE UNIQUE INDEX uq_secretary_grants_active
ON secretary_assistance_grants (
    organization_id,
    secretary_principal_id,
    context_key,
    assistance_operation,
    port_contract_version
)
WHERE revoked_at IS NULL;

CREATE INDEX ix_decisions_organization_status
ON decisions (
    organization_id,
    status,
    updated_at DESC
);

CREATE INDEX ix_decisions_related_work
ON decisions (
    organization_id,
    related_work_id
);

CREATE INDEX ix_decision_revisions_decision_number
ON decision_revisions (
    decision_id,
    revision_number DESC
);

CREATE INDEX ix_decisions_in_review
ON decisions (
    organization_id,
    submitted_at
)
WHERE status = 'InReview';

CREATE UNIQUE INDEX uq_decisions_one_in_review_blocking_per_work
ON decisions (
    organization_id,
    related_work_id
)
WHERE status = 'InReview'
  AND is_blocking = TRUE;

ALTER TABLE memories
ADD CONSTRAINT ck_memories_status
CHECK (
    status IN (
        'Generated',
        'InReview',
        'Rejected',
        'Approved'
    )
);

CREATE UNIQUE INDEX uq_memories_active_work
ON memories (
    organization_id,
    source_work_id
)
WHERE is_active = true;

CREATE UNIQUE INDEX uq_memory_revisions_one_generated
ON memory_revisions (
    memory_id
)
WHERE revision_status = 'Generated';

CREATE INDEX ix_memories_organization_status
ON memories (
    organization_id,
    status
);

CREATE INDEX ix_memories_source_work
ON memories (
    organization_id,
    source_work_id
);

CREATE INDEX ix_memories_in_review
ON memories (
    organization_id,
    submitted_at
)
WHERE status = 'InReview';

CREATE INDEX ix_memory_revisions_memory_number
ON memory_revisions (
    memory_id,
    revision_number DESC
);

ALTER TABLE human_identities
ADD CONSTRAINT ck_human_identities_status
CHECK (
    status IN (
        'Active',
        'Disabled'
    )
);

CREATE UNIQUE INDEX uq_authentication_subjects_active
ON authentication_subjects (
    provider,
    issuer,
    subject
)
WHERE unlinked_at IS NULL;

CREATE INDEX ix_human_identities_status
ON human_identities (
    status
);

CREATE INDEX ix_human_identities_primary_email
ON human_identities (
    primary_email_normalized
);

CREATE INDEX ix_authentication_subjects_identity
ON authentication_subjects (
    identity_id
)
WHERE unlinked_at IS NULL;

ALTER TABLE organizations
ADD CONSTRAINT ck_organizations_status
CHECK (
    status IN (
        'Active',
        'Suspended',
        'Archived'
    )
);

CREATE INDEX ix_organizations_status
ON organizations (
    status
);

ALTER TABLE memberships
ADD CONSTRAINT ck_memberships_status
CHECK (
    status IN (
        'Invited',
        'Active',
        'Suspended',
        'Revoked'
    )
);

ALTER TABLE memberships
ADD CONSTRAINT ck_memberships_identity_state
CHECK (
    (
        status = 'Invited'
        AND (
            identity_id IS NOT NULL
            OR pending_invitee_email_normalized IS NOT NULL
        )
    )
    OR
    (
        status IN (
            'Active',
            'Suspended'
        )
        AND identity_id IS NOT NULL
    )
    OR
    status = 'Revoked'
);

CREATE UNIQUE INDEX uq_memberships_organization_identity
ON memberships (
    organization_id,
    identity_id
)
WHERE identity_id IS NOT NULL;

CREATE UNIQUE INDEX uq_memberships_pending_invitation
ON memberships (
    organization_id,
    pending_invitee_email_normalized
)
WHERE status = 'Invited'
  AND identity_id IS NULL;

ALTER TABLE membership_role_assignments
ADD CONSTRAINT ck_membership_role_assignments_role
CHECK (
    role IN (
        'OrganizationOwner',
        'OrganizationAdmin',
        'Member',
        'Reviewer'
    )
);

CREATE UNIQUE INDEX uq_membership_role_assignments_active
ON membership_role_assignments (
    membership_id,
    role
)
WHERE revoked_at IS NULL;

CREATE INDEX ix_membership_roles_active_owners
ON membership_role_assignments (
    organization_id,
    membership_id
)
WHERE role = 'OrganizationOwner'
  AND revoked_at IS NULL;

ALTER TABLE organization_invitations
ADD CONSTRAINT ck_organization_invitations_status
CHECK (
    status IN (
        'Pending',
        'Consumed',
        'Revoked',
        'Expired'
    )
);

ALTER TABLE organization_invitations
ADD CONSTRAINT uq_organization_invitations_token_hash
UNIQUE (
    token_hash
);

ALTER TABLE organization_invitations
ADD CONSTRAINT uq_organization_invitations_membership_version
UNIQUE (
    membership_id,
    invitation_version
);

CREATE INDEX ix_memberships_organization_status
ON memberships (
    organization_id,
    status
);

CREATE INDEX ix_memberships_identity
ON memberships (
    identity_id
)
WHERE identity_id IS NOT NULL;

CREATE INDEX ix_memberships_pending_email
ON memberships (
    organization_id,
    pending_invitee_email_normalized
)
WHERE status = 'Invited';

ALTER TABLE authorization_audit_records
ADD CONSTRAINT ck_authorization_audit_outcome
CHECK (
    outcome IN (
        'Allow',
        'Deny'
    )
);

CREATE INDEX ix_authorization_audit_correlation
ON authorization_audit_records (
    correlation_id
);

CREATE INDEX ix_authorization_audit_organization_time
ON authorization_audit_records (
    organization_id,
    evaluated_at DESC
);

CREATE INDEX ix_authorization_audit_principal_time
ON authorization_audit_records (
    principal_id,
    evaluated_at DESC
);

CREATE INDEX ix_authorization_audit_denials
ON authorization_audit_records (
    organization_id,
    reason_code,
    evaluated_at DESC
)
WHERE outcome = 'Deny';

ALTER TABLE outbox_messages
ADD CONSTRAINT uq_outbox_stream_position
UNIQUE (
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_sequence
);

CREATE INDEX ix_notifications_recipient_unacknowledged
ON notifications (
    organization_id,
    recipient_membership_id,
    occurred_at DESC
)
WHERE acknowledged_at IS NULL;

CREATE UNIQUE INDEX uq_event_replays_active_delivery
ON event_replays (
    consumer_name,
    original_event_id
)
WHERE status IN (
    'Requested',
    'Validating',
    'Running'
);

CREATE INDEX ix_event_replays_runnable
ON event_replays (
    status,
    next_attempt_at,
    created_at
)
WHERE status IN (
    'Requested',
    'Validating'
);

CREATE INDEX ix_event_replays_expired_claim
ON event_replays (
    locked_until
)
WHERE status = 'Running';

CREATE UNIQUE INDEX uq_memory_generation_operation_identity
ON memory_generation_operations (
    organization_id,
    work_id,
    generation_policy_version
);

CREATE INDEX ix_memory_generation_runnable
ON memory_generation_operations (
    status,
    next_attempt_at
)
WHERE status IN (
    'Pending',
    'RetryPending'
);

CREATE INDEX ix_memory_generation_expired_claim
ON memory_generation_operations (
    locked_until
)
WHERE status = 'Generating';

CREATE INDEX ix_decisions_review_queue
ON decisions (
    organization_id,
    submitted_at,
    decision_id
)
WHERE status = 'InReview';

CREATE INDEX ix_memories_review_queue
ON memories (
    organization_id,
    submitted_at,
    memory_id
)
WHERE status = 'InReview'
  AND is_active = true;

CREATE INDEX ix_outbox_messages_pending
ON outbox_messages (
    next_attempt_at,
    recorded_at,
    outbox_id
)
WHERE status = 'Pending';

CREATE INDEX ix_processed_events_pending
ON processed_events (
    first_received_at,
    consumer_name,
    event_id
)
WHERE status = 'Pending';

CREATE INDEX ix_processed_events_retry
ON processed_events (
    next_attempt_at,
    first_received_at,
    consumer_name,
    event_id
)
WHERE status = 'RetryPending';

CREATE INDEX ix_processed_events_expired_claim
ON processed_events (
    locked_until,
    consumer_name,
    event_id
)
WHERE status = 'Processing';

CREATE INDEX ix_processed_events_blocked
ON processed_events (
    consumer_name,
    organization_id,
    ordering_key_type,
    ordering_key,
    source_sequence
)
WHERE status = 'Blocked';

CREATE UNIQUE INDEX uq_consumer_ordering_state_organization
ON consumer_ordering_state (
    consumer_name,
    organization_id,
    ordering_key_type,
    ordering_key
)
WHERE organization_id IS NOT NULL;

CREATE INDEX ix_decisions_review_queue_covering
ON decisions (
    organization_id,
    submitted_at,
    decision_id
)
INCLUDE (
    submitted_revision_id,
    submitted_by_identity_id
)
WHERE status = 'InReview';

ALTER TABLE outbox_messages
ADD CONSTRAINT uq_outbox_event_destination
UNIQUE (event_id, destination);

ALTER TABLE outbox_messages
ADD CONSTRAINT ck_outbox_status
CHECK (
    status IN (
        'Pending',
        'Claimed',
        'Published',
        'Failed'
    )
);

ALTER TABLE outbox_messages
ADD CONSTRAINT ck_outbox_schema_version
CHECK (
    schema_version > 0
);

ALTER TABLE outbox_messages
ADD CONSTRAINT ck_outbox_attempt_count
CHECK (
    attempt_count >= 0
);

CREATE INDEX ix_outbox_pending
ON outbox_messages (
    next_attempt_at,
    recorded_at
)
WHERE status = 'Pending';

CREATE INDEX ix_outbox_claim_expiry
ON outbox_messages (
    locked_until
)
WHERE status = 'Claimed';

CREATE INDEX ix_outbox_aggregate_stream
ON outbox_messages (
    aggregate_type,
    aggregate_id,
    aggregate_version
);

CREATE INDEX ix_outbox_correlation
ON outbox_messages (
    correlation_id
);

CREATE INDEX ix_outbox_organization
ON outbox_messages (
    organization_id,
    recorded_at
);
