import{describe,expect,it,vi}from'vitest';
import{GenerateMemoryHandler}from'./generate-memory.js';
import type{GenerationClaim,MemoryCandidate,MemoryGenerationOperation,MemoryGenerationPorts,MemorySourceSnapshot,WorkCompletedForMemory}from'./ports.js';
const event:WorkCompletedForMemory={eventId:'event-a',organizationId:'org-a',workId:'work-a',workVersion:4,workRevisionId:'revision-a',completedAt:new Date(0),completedByMembershipId:'member-a'};
const source={title:'Completed work',completionSummary:'Done'};
const snapshot:MemorySourceSnapshot={snapshotId:'snapshot-a',organizationId:'org-a',sourceWorkId:'work-a',workCompletedEventId:'event-a',workVersion:4,workRevisionId:'revision-a',content:source,sourceHash:'hash',capturedAt:new Date(0)};
const claim:GenerationClaim={operationId:'operation-a',organizationId:'org-a',claimVersion:1,lockedBy:'worker-a',lockedUntil:new Date(10000),sourceSnapshot:snapshot,providerInputHash:'hash',generationPolicyVersion:'generation-v1',promptPolicyVersion:'prompt-v1'};
const candidate:MemoryCandidate={schemaVersion:1,content:{title:'Memory',summary:'Summary',outcome:'Done',lessonsObserved:[],unresolvedItems:[],additionalContext:''},sourceSnapshotId:'snapshot-a',sourceSnapshotHash:'hash',providerInputHash:'hash',provider:'provider-a',model:'model-a',promptPolicyVersion:'prompt-v1',generationPolicyVersion:'generation-v1'};
function harness(generate=vi.fn(()=>Promise.resolve(candidate))){const operation:MemoryGenerationOperation={operationId:'operation-a',organizationId:'org-a',sourceWorkId:'work-a',sourceEventId:'event-a',sourceSnapshotId:'snapshot-a',sourceSnapshotHash:'hash',providerInputHash:'hash',generationPolicyVersion:'generation-v1',promptPolicyVersion:'prompt-v1',status:'Pending',attemptCount:0,claimVersion:0};const finalize=vi.fn(()=>Promise.resolve());const fail=vi.fn(()=>Promise.resolve());const ports:MemoryGenerationPorts={store:{initialize:()=>Promise.resolve(operation),claim:()=>Promise.resolve(claim),finalize,fail,abandon:()=>Promise.resolve()},source:{capture:()=>Promise.resolve(source)},provider:{generate},ids:{operationId:()=>operation.operationId,snapshotId:()=>snapshot.snapshotId,memoryId:()=>'memory-a',eventId:()=>'memory-event-a',revisionId:()=>'memory-revision-a',reviewId:()=>'review-a',hash:()=>'hash'},clock:{now:()=>new Date(1000)},workerId:'worker-a',timeoutMs:1000,leaseMs:10000,maxAttempts:3,generationPolicyVersion:'generation-v1',promptPolicyVersion:'prompt-v1'};return{handler:new GenerateMemoryHandler(ports),finalize,fail,generate};}
describe('GenerateMemoryHandler',()=>{
 it('commits generated Memory only after the provider returns a provenance-bound candidate',async()=>{const h=harness();expect(await h.handler.initialize(event)).toBe('operation-a');expect(await h.handler.run('org-a','operation-a')).toBe('Generated');expect(h.finalize).toHaveBeenCalledOnce();expect(h.finalize.mock.calls[0]?.[1].state).toMatchObject({status:'Generated',organizationId:'org-a',provenance:{sourceWorkId:'work-a',sourceSnapshotId:'snapshot-a'}});});
 it('rejects a stale or mismatched provider result without creating Memory',async()=>{const h=harness(vi.fn(()=>Promise.resolve({...candidate,sourceSnapshotHash:'other'})));expect(await h.handler.run('org-a','operation-a')).toBe('Failed');expect(h.finalize).not.toHaveBeenCalled();expect(h.fail).toHaveBeenCalledWith(claim,expect.objectContaining({retryable:false}),new Date(1000));});
 it('records transient provider failure for bounded retry',async()=>{const h=harness(vi.fn(()=>Promise.reject(new Error('timeout'))));expect(await h.handler.run('org-a','operation-a')).toBe('RetryPending');expect(h.finalize).not.toHaveBeenCalled();expect(h.fail).toHaveBeenCalledWith(claim,expect.objectContaining({retryable:true}),new Date(1000));});
});
