import{Memory,MemoryInvariantViolation}from'../domain/memory.js';
import type{GenerationClaim,MemoryCandidate,MemoryGenerationPorts,WorkCompletedForMemory}from'./ports.js';
export class MemoryGenerationConflict extends Error{}
export class MemoryGenerationNotClaimed extends Error{}

const candidateValid=(candidate:MemoryCandidate,claim:GenerationClaim):boolean=>candidate.sourceSnapshotId===claim.sourceSnapshot.snapshotId&&candidate.sourceSnapshotHash===claim.sourceSnapshot.sourceHash&&candidate.providerInputHash===claim.providerInputHash&&candidate.promptPolicyVersion===claim.promptPolicyVersion&&candidate.generationPolicyVersion===claim.generationPolicyVersion&&candidate.provider.trim().length>0&&candidate.model.trim().length>0;

export class GenerateMemoryHandler{
 constructor(private readonly ports:MemoryGenerationPorts){}
 async initialize(event:WorkCompletedForMemory):Promise<string>{const source=await this.ports.source.capture(event);if(source===undefined)throw new MemoryGenerationConflict('Completed Work source was not found');const sourceHash=this.ports.ids.hash(source);const snapshotId=this.ports.ids.snapshotId();const providerInputHash=this.ports.ids.hash({source,sourceSnapshotId:snapshotId,promptPolicyVersion:this.ports.promptPolicyVersion,generationPolicyVersion:this.ports.generationPolicyVersion});const operation=await this.ports.store.initialize(event,{operationId:this.ports.ids.operationId(),snapshotId,sourceHash,providerInputHash,generationPolicyVersion:this.ports.generationPolicyVersion,promptPolicyVersion:this.ports.promptPolicyVersion,capturedAt:this.ports.clock.now()});return operation.operationId;}
 async run(organizationId:string,operationId:string):Promise<'Generated'|'NotClaimed'|'RetryPending'|'Failed'>{const now=this.ports.clock.now();const claim=await this.ports.store.claim(organizationId,operationId,this.ports.workerId,new Date(now.getTime()+this.ports.leaseMs),now);if(claim===undefined)return'NotClaimed';const controller=new AbortController();const timeout=setTimeout(()=>{controller.abort();},this.ports.timeoutMs);try{const candidate=await this.ports.provider.generate({source:claim.sourceSnapshot.content,sourceSnapshotId:claim.sourceSnapshot.snapshotId,sourceSnapshotHash:claim.sourceSnapshot.sourceHash,providerInputHash:claim.providerInputHash,promptPolicyVersion:claim.promptPolicyVersion,generationPolicyVersion:claim.generationPolicyVersion,signal:controller.signal});if(!candidateValid(candidate,claim))throw new MemoryGenerationConflict('Provider candidate did not match the claimed provenance');const memory=Memory.generate({memoryId:this.ports.ids.memoryId(),organizationId,content:candidate.content,provenance:{sourceWorkId:claim.sourceSnapshot.sourceWorkId,sourceSnapshotId:claim.sourceSnapshot.snapshotId,sourceSnapshotHash:claim.sourceSnapshot.sourceHash,generationOperationId:claim.operationId,providerInputHash:claim.providerInputHash,provider:candidate.provider,model:candidate.model,promptPolicyVersion:claim.promptPolicyVersion,generationPolicyVersion:claim.generationPolicyVersion},actor:{actorType:'System',systemId:'memory-generation-v1'},now:this.ports.clock.now(),ids:this.ports.ids});await this.ports.store.finalize(claim,memory,memory.pullEvents(),this.ports.clock.now());return'Generated';}catch(error){const retryable=!(error instanceof MemoryGenerationConflict||error instanceof MemoryInvariantViolation);const exhausted=claim.claimVersion>=this.ports.maxAttempts;await this.ports.store.fail(claim,{code:error instanceof Error?error.name:'UnknownProviderFailure',retryable:retryable&&!exhausted,nextAttemptAt:retryable&&!exhausted?new Date(this.ports.clock.now().getTime()+1000*Math.min(300,2**claim.claimVersion)):undefined},this.ports.clock.now());return retryable&&!exhausted?'RetryPending':'Failed';}finally{clearTimeout(timeout);}}
}
