import{describe,expect,it}from'vitest';
import type{HumanMemberPrincipal}from'../../identity-organization/public.js';
import{Memory,type MemoryContent}from'../domain/memory.js';
import{MemoryNotFound,MemoryReviewService}from'./memory-review-service.js';
const principal:HumanMemberPrincipal={principalType:'HumanMember',principalId:'member-a',identityId:'human-a',membershipId:'member-a',organizationId:'org-a',roles:['Member']};
const content:MemoryContent={title:'Memory',summary:'Summary',outcome:'Done',lessonsObserved:[],unresolvedItems:[],additionalContext:''};
function harness(){let id=0;const ids={operationId:()=>'operation-a',snapshotId:()=>'snapshot-a',memoryId:()=>'memory-a',eventId:()=>`event-${String(++id)}`,revisionId:()=>`revision-${String(++id)}`,reviewId:()=>`review-${String(++id)}`,hash:()=>'hash'};let state=Memory.generate({memoryId:'memory-a',organizationId:'org-a',content,provenance:{sourceWorkId:'work-a',sourceSnapshotId:'snapshot-a',sourceSnapshotHash:'hash',generationOperationId:'operation-a',providerInputHash:'hash',provider:'provider',model:'model',promptPolicyVersion:'v1',generationPolicyVersion:'v1'},actor:{actorType:'System',systemId:'generator'},now:new Date(0),ids}).state;const events:unknown[]=[];const service=new MemoryReviewService({transactions:{transaction:operation=>operation()},repository:{get:(organizationId,memoryId)=>Promise.resolve(state.organizationId===organizationId&&state.memoryId===memoryId?state:undefined),getByWork:()=>Promise.resolve(undefined),add:()=>Promise.resolve(),save:(_organizationId,memory)=>{state=memory.state;return Promise.resolve();}},authorization:{require:()=>Promise.resolve()},events:{append:batch=>{events.push(...batch);return Promise.resolve();}},clock:{now:()=>new Date(1)},ids});return{service,state:()=>state,events};}
describe('MemoryReviewService',()=>{
 it('requires separate Human submission and review commands',async()=>{const h=harness();await h.service.submit(principal,'org-a','memory-a',1);await h.service.approve(principal,'org-a','memory-a',2,'Confirmed');expect(h.state()).toMatchObject({status:'Approved',version:3});expect(h.events).toHaveLength(2);});
 it('fails closed before lookup for another Organization',async()=>{const h=harness();await expect(h.service.submit(principal,'org-b','memory-a',1)).rejects.toBeInstanceOf(MemoryNotFound);expect(h.state()).toMatchObject({status:'Generated'});});
});
