import type{HumanMemberPrincipal}from'../../identity-organization/public.js';
import{Memory,type MemoryContent}from'../domain/memory.js';
import type{MemoryClock,MemoryEventWriter,MemoryIds,MemoryRepository,MemoryReviewAuthorization,MemoryReviewTransaction}from'./ports.js';
export class MemoryNotFound extends Error{constructor(){super('The resource was not found or is not available');}}
export class MemoryReviewService{
 constructor(private readonly dependencies:{transactions:MemoryReviewTransaction;repository:MemoryRepository;authorization:MemoryReviewAuthorization;events:MemoryEventWriter;clock:MemoryClock;ids:MemoryIds}){}
 edit(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number,content:MemoryContent):Promise<void>{return this.mutate(principal,organizationId,memoryId,expectedVersion,'memory.edit',memory=>{memory.edit(this.actor(principal),content,this.dependencies.clock.now());});}
 submit(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number):Promise<void>{return this.mutate(principal,organizationId,memoryId,expectedVersion,'memory.submit',memory=>{memory.submit(this.actor(principal),this.dependencies.clock.now());});}
 approve(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number,confirmation?:string):Promise<void>{return this.mutate(principal,organizationId,memoryId,expectedVersion,'memory.review',memory=>{memory.approve(this.actor(principal),confirmation,this.dependencies.clock.now());});}
 reject(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number,reason:string):Promise<void>{return this.mutate(principal,organizationId,memoryId,expectedVersion,'memory.review',memory=>{memory.reject(this.actor(principal),reason,this.dependencies.clock.now());});}
 reopen(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number):Promise<void>{return this.mutate(principal,organizationId,memoryId,expectedVersion,'memory.reopen',memory=>{memory.reopen(this.actor(principal),this.dependencies.clock.now());});}
 private mutate(principal:HumanMemberPrincipal,organizationId:string,memoryId:string,expectedVersion:number,permission:'memory.edit'|'memory.submit'|'memory.review'|'memory.reopen',change:(memory:Memory)=>void):Promise<void>{return this.dependencies.transactions.transaction(async()=>{if(principal.organizationId!==organizationId)throw new MemoryNotFound();await this.dependencies.authorization.require(permission,organizationId,principal.membershipId);const state=await this.dependencies.repository.get(organizationId,memoryId);if(state===undefined||state.version!==expectedVersion)throw new MemoryNotFound();const memory=Memory.rehydrate(state,this.dependencies.ids);change(memory);await this.dependencies.repository.save(organizationId,memory,expectedVersion);await this.dependencies.events.append(memory.pullEvents());});}
 private actor(principal:HumanMemberPrincipal){return{actorType:'HumanMember' as const,identityId:principal.identityId,membershipId:principal.membershipId};}
}
