import type{HumanMemberPrincipal}from'../../identity-organization/public.js';
import{Work}from'../../work/public.js';
import{Decision,type DecisionContent,type HumanDecisionActor}from'../domain/decision.js';
import{DecisionConcurrencyConflict,DecisionNotFound,DecisionPermissionDenied}from'./decision-service.js';
import type{CoordinatedWorkRepository,DecisionClock,DecisionCommandLedger,DecisionIds,DecisionOutbox,DecisionRepository,DecisionTransaction}from'./ports.js';
type Dependencies={transactions:DecisionTransaction;work:CoordinatedWorkRepository;decisions:DecisionRepository;commands:DecisionCommandLedger;outbox:DecisionOutbox;clock:DecisionClock;ids:DecisionIds};
export class RequestBlockingDecisionService{
 constructor(private readonly dependencies:Dependencies){}
 execute(context:{commandId:string;organizationId:string;principal:HumanMemberPrincipal},input:{workId:string;workExpectedVersion:number;decisionId:string;content:DecisionContent}):Promise<unknown>{
  return this.dependencies.transactions.transaction(async()=>{if(context.principal.organizationId!==context.organizationId)throw new DecisionPermissionDenied();const prior=await this.dependencies.commands.result(context.commandId);if(prior!==undefined)return prior;const workState=await this.dependencies.work.getForUpdate(context.organizationId,input.workId);if(!workState)throw new DecisionNotFound();if(workState.version!==input.workExpectedVersion)throw new DecisionConcurrencyConflict();const actor:HumanDecisionActor={actorType:'HumanMember',identityId:context.principal.identityId,membershipId:context.principal.membershipId};const decision=Decision.create({decisionId:input.decisionId,organizationId:context.organizationId,relatedWorkId:input.workId,isBlocking:true,content:input.content,actor,now:this.dependencies.clock.now(),ids:this.dependencies.ids});const reference=decision.submit(actor,this.dependencies.clock.now());const work=Work.rehydrate(workState,()=>this.dependencies.ids.eventId());work.requestBlockingDecision(actor,reference,this.dependencies.clock.now());await this.dependencies.decisions.add(context.organizationId,decision);await this.dependencies.work.save(context.organizationId,work,input.workExpectedVersion);await this.dependencies.outbox.appendDomain(decision.pullEvents());await this.dependencies.outbox.appendWork(work.pullEvents());const result={workId:input.workId,decisionId:input.decisionId,workVersion:work.state.version,decisionVersion:decision.state.version,reference};await this.dependencies.commands.record(context.commandId,context.organizationId,'RequestBlockingDecision',result);return result;});
 }
}
