import type{HumanMemberPrincipal}from'../../identity-organization/public.js';
import{Decision,type DecisionContent,type DecisionEvent,type HumanDecisionActor}from'../domain/decision.js';
import type{DecisionClock,DecisionCommandLedger,DecisionIds,DecisionOutbox,DecisionRepository,DecisionTransaction}from'./ports.js';
export class DecisionNotFound extends Error{constructor(){super('The resource was not found or is not available');}}
export class DecisionPermissionDenied extends Error{constructor(){super('The resource was not found or is not available');}}
export class DecisionConcurrencyConflict extends Error{}
type Context={readonly commandId:string;readonly organizationId:string;readonly principal:HumanMemberPrincipal};
type Dependencies={readonly transactions:DecisionTransaction;readonly repository:DecisionRepository;readonly commands:DecisionCommandLedger;readonly outbox:DecisionOutbox;readonly ids:DecisionIds;readonly clock:DecisionClock};
export class DecisionService{
 constructor(private readonly dependencies:Dependencies){}
 create(context:Context,input:{decisionId:string;relatedWorkId:string;isBlocking:boolean;content:DecisionContent}):Promise<unknown>{return this.execute(context,'CreateDecision',async()=>{const decision=Decision.create({...input,organizationId:context.organizationId,actor:this.actor(context),now:this.dependencies.clock.now(),ids:this.dependencies.ids});await this.dependencies.repository.add(context.organizationId,decision);await this.persistEvents(decision.pullEvents());return{decisionId:input.decisionId,status:decision.state.status,version:decision.state.version};});}
 edit(context:Context,input:{decisionId:string;expectedVersion:number;content:DecisionContent}):Promise<unknown>{return this.mutate(context,input.decisionId,input.expectedVersion,'EditDecision',(decision)=>{decision.editDraft(this.actor(context),input.content,this.dependencies.clock.now());});}
 submit(context:Context,input:{decisionId:string;expectedVersion:number}):Promise<unknown>{return this.mutate(context,input.decisionId,input.expectedVersion,'SubmitDecision',(decision)=>decision.submit(this.actor(context),this.dependencies.clock.now()));}
 approve(context:Context,input:{decisionId:string;expectedVersion:number;rationale?:string|undefined}):Promise<unknown>{this.requireReviewer(context.principal);return this.resolve(context,input,'Approved');}
 reject(context:Context,input:{decisionId:string;expectedVersion:number;rationale?:string|undefined}):Promise<unknown>{this.requireReviewer(context.principal);return this.resolve(context,input,'Rejected');}
 withdraw(context:Context,input:{decisionId:string;expectedVersion:number;rationale?:string|undefined}):Promise<unknown>{return this.resolve(context,input,'Withdrawn');}
 private resolve(context:Context,input:{decisionId:string;expectedVersion:number;rationale?:string|undefined},outcome:'Approved'|'Rejected'|'Withdrawn'):Promise<unknown>{return this.mutate(context,input.decisionId,input.expectedVersion,`${outcome}Decision`,(decision)=>{if(outcome==='Approved')decision.approve(this.actor(context),input.rationale,this.dependencies.clock.now());else if(outcome==='Rejected')decision.reject(this.actor(context),input.rationale,this.dependencies.clock.now());else decision.withdraw(this.actor(context),input.rationale,this.dependencies.clock.now());});}
 private mutate(context:Context,decisionId:string,expectedVersion:number,type:string,change:(decision:Decision)=>unknown):Promise<unknown>{return this.execute(context,type,async()=>{const state=await this.dependencies.repository.get(context.organizationId,decisionId);if(!state)throw new DecisionNotFound();if(state.version!==expectedVersion)throw new DecisionConcurrencyConflict();const decision=Decision.rehydrate(state,this.dependencies.ids);const detail=change(decision);await this.dependencies.repository.save(context.organizationId,decision,expectedVersion);await this.persistEvents(decision.pullEvents());return{decisionId,status:decision.state.status,version:decision.state.version,detail};});}
 private execute(context:Context,type:string,operation:()=>Promise<unknown>):Promise<unknown>{return this.dependencies.transactions.transaction(async()=>{this.requireScope(context.principal,context.organizationId);const prior=await this.dependencies.commands.result(context.commandId);if(prior!==undefined)return prior;const result=await operation();await this.dependencies.commands.record(context.commandId,context.organizationId,type,result);return result;});}
 private async persistEvents(events:readonly DecisionEvent[]):Promise<void>{await this.dependencies.outbox.appendDomain(events);for(const event of events){if(event.eventType==='DecisionApproved'||event.eventType==='DecisionRejected'||event.eventType==='DecisionWithdrawn'){const outcome=event.eventType==='DecisionApproved'?'Approved':event.eventType==='DecisionRejected'?'Rejected':'Withdrawn';await this.dependencies.outbox.appendOutcome({eventId:event.eventId,organizationId:event.organizationId,workId:event.relatedWorkId,decisionId:event.decisionId,revisionNumber:Number(event.payload.revisionNumber),submittedSnapshotId:String(event.payload.submittedSnapshotId),decisionAggregateVersion:event.aggregateVersion,outcome,resolvedByMembershipId:event.actor.membershipId,resolvedAt:event.occurredAt});}}}
 private requireScope(principal:HumanMemberPrincipal,organizationId:string):void{if(principal.organizationId!==organizationId)throw new DecisionPermissionDenied();}
 private requireReviewer(principal:HumanMemberPrincipal):void{if(!principal.roles.some(role=>role==='Reviewer'||role==='OrganizationOwner'||role==='OrganizationAdmin'))throw new DecisionPermissionDenied();}
 private actor(context:Context):HumanDecisionActor{return{actorType:'HumanMember',identityId:context.principal.identityId,membershipId:context.principal.membershipId};}
}
