/**
 * Deterministic Memory generator — generation policy version 1.
 *
 * Produces a draft from the provider input and nothing else. It invents
 * nothing, which is what makes it safe to approve: every sentence is a
 * rearrangement of what the Work already recorded.
 *
 * It is not a fallback for a failed provider call, and it is not a stub waiting
 * to be deleted. It is the generator used when no provider credential is
 * configured, so the whole loop — completion, draft, correction, review,
 * approval — runs on a laptop with no account and no spend. ADR-0016 pins the
 * real policy at version 2; this stays version 1 permanently, because Memories
 * generated by it must remain distinguishable forever.
 */

import { createHash } from "node:crypto";

import type { GeneratedContent } from "@aios/domain";
import type { MemoryGenerator, ProviderInput } from "@aios/application";

export const DETERMINISTIC_POLICY_VERSION = 1;

const hashOf = (content: string): string =>
  createHash("sha256").update(content).digest("hex");

export class DeterministicMemoryGenerator implements MemoryGenerator {
  readonly policyVersion = DETERMINISTIC_POLICY_VERSION;
  readonly promptTemplateVersion = 1;
  readonly outputSchemaVersion = 1;
  readonly modelReference = "deterministic";

  async generate(input: {
    providerInput: ProviderInput;
    providerInputHash: string;
  }): Promise<GeneratedContent> {
    const source = input.providerInput;

    const lines = [
      `# ${source.title}`,
      "",
      source.description ?? "_No description was recorded._",
      "",
      "## Outcome",
      "",
      source.completionSummary ?? "_No completion summary was recorded._",
      "",
      "## What this draft is based on",
      "",
      `- Work ${source.workId}`,
      `- Completed at ${source.completedAt ?? "unknown"}`,
      source.decision === undefined
        ? "- Completion required no Decision approval"
        : `- Completion required an approved Decision (${source.decision.decisionId})`,
      "",
      "---",
      "",
      "_Generated without a language model. This draft repeats what the Work",
      "recorded and draws no conclusions; a reviewer must add the lessons._",
    ];

    const content = lines.join("\n");

    return {
      title: source.title,
      summary: source.completionSummary ?? "Completed without a recorded summary.",
      content,
      sourceReferences: [
        `work:${source.workId}`,
        ...(source.decision === undefined
          ? []
          : [`decision:${source.decision.decisionId}`]),
      ],
      contentHash: hashOf(content),
    };
  }
}
